#!/usr/bin/env bash
# Blocks forbidden attribution text in commit messages and optional PR text.
set -euo pipefail

BASE_REF="origin/main"
BASE_SHA=""
HEAD_SHA="HEAD"
PR_TITLE=""
PR_BODY=""
PR_BODY_FILE=""

FORBIDDEN_REGEX='made[- ]with:|made with[[:space:]]|co-authored-by:[[:space:]]|generated by[[:space:]]|powered by[[:space:]]'

usage() {
    cat <<'EOF'
Usage: attribution-guard.sh [options]
  --base-ref <ref>    Base ref for merge-base scan (default: origin/main)
  --base-sha <sha>    Explicit base SHA
  --head-sha <sha>    Explicit head SHA (default: HEAD)
  --title <text>      PR title text
  --body <text>       PR body text
  --body-file <path>  Read PR body from file
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --base-ref) BASE_REF="$2"; shift 2 ;;
        --base-sha) BASE_SHA="$2"; shift 2 ;;
        --head-sha) HEAD_SHA="$2"; shift 2 ;;
        --title) PR_TITLE="$2"; shift 2 ;;
        --body) PR_BODY="$2"; shift 2 ;;
        --body-file) PR_BODY_FILE="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
    esac
done

if [[ -n "${PR_BODY_FILE}" ]]; then
    [[ -f "${PR_BODY_FILE}" ]] || { echo "Missing --body-file: ${PR_BODY_FILE}" >&2; exit 1; }
    PR_BODY="$(<"${PR_BODY_FILE}")"
fi

BASE="${BASE_SHA}"
if [[ -z "${BASE}" ]]; then
    BASE="$(git merge-base "${BASE_REF}" "${HEAD_SHA}")"
fi

MESSAGES="$(git log --format=%B "${BASE}..${HEAD_SHA}")"
if printf '%s\n' "${MESSAGES}" | grep -Eqi "${FORBIDDEN_REGEX}"; then
    echo "Forbidden attribution detected in commit messages." >&2
    exit 1
fi

TEXT="${PR_TITLE}"$'\n'"${PR_BODY}"
if printf '%s\n' "${TEXT}" | grep -Eqi "${FORBIDDEN_REGEX}"; then
    echo "Forbidden attribution detected in PR title/body." >&2
    exit 1
fi

echo "Attribution guard passed."
