#!/usr/bin/env bash
# =============================================================================
# First-Run Setup — Validates prerequisites and generates .env with secrets
#
# What it does:
#   1. Checks that Docker and Docker Compose are installed
#   2. Copies .env.example to .env if it doesn't exist
#   3. Generates random secrets for CMD_SESSION_SECRET and POSTGRES_PASSWORD
#   4. Creates the backups/ directory
#
# This script is idempotent — safe to run multiple times. It never overwrites
# an existing .env file (your configuration is preserved).
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for terminal output (disabled if not a TTY)
if [ -t 1 ]; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    RED='\033[0;31m'
    NC='\033[0m'
else
    GREEN='' YELLOW='' RED='' NC=''
fi

info()  { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# -- Step 1: Check prerequisites ---------------------------------------------

check_command() {
    if ! command -v "$1" &>/dev/null; then
        error "$1 is not installed. Please install it first."
        error "  See: $2"
        exit 1
    fi
}

echo "Checking prerequisites..."
check_command "docker" "https://docs.docker.com/get-docker/"

# Docker Compose v2 is a docker subcommand, v1 was a separate binary
if docker compose version &>/dev/null; then
    info "Docker Compose (v2) found"
elif command -v docker-compose &>/dev/null; then
    warn "docker-compose (v1) found — consider upgrading to Docker Compose v2"
else
    error "Docker Compose not found. Install Docker Desktop or the compose plugin."
    error "  See: https://docs.docker.com/compose/install/"
    exit 1
fi

# Verify Docker daemon is running
if ! docker info &>/dev/null; then
    error "Docker daemon is not running. Start Docker and try again."
    exit 1
fi
info "Docker is running"

# -- Step 2: Generate .env from template -------------------------------------

ENV_FILE="$PROJECT_DIR/.env"
ENV_EXAMPLE="$PROJECT_DIR/.env.example"

generate_secret() {
    # Generate a cryptographically random 64-character hex string.
    # Works on Linux (urandom), macOS (urandom), and falls back to openssl.
    if command -v openssl &>/dev/null; then
        openssl rand -hex 32
    elif [ -r /dev/urandom ]; then
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    else
        error "Cannot generate random secret — install openssl"
        exit 1
    fi
}

if [ -f "$ENV_FILE" ]; then
    info ".env already exists — skipping generation (your config is preserved)"
else
    if [ ! -f "$ENV_EXAMPLE" ]; then
        error ".env.example not found at $ENV_EXAMPLE"
        exit 1
    fi

    echo "Generating .env with random secrets..."

    SESSION_SECRET=$(generate_secret)
    DB_PASSWORD=$(generate_secret)

    # Copy the template and replace placeholder values with real secrets
    sed \
        -e "s|CMD_SESSION_SECRET=<auto-generated>|CMD_SESSION_SECRET=${SESSION_SECRET}|" \
        -e "s|POSTGRES_PASSWORD=<auto-generated>|POSTGRES_PASSWORD=${DB_PASSWORD}|" \
        "$ENV_EXAMPLE" > "$ENV_FILE"

    info ".env created with auto-generated secrets"
fi

# -- Step 3: Create directories -----------------------------------------------

mkdir -p "$PROJECT_DIR/backups"
info "backups/ directory ready"

echo ""
info "Setup complete. Run 'make up' to start HedgeDoc."
